from fastapi import APIRouter, HTTPException
from typing import Dict, Any, Optional, List
import logging

from application.langgraph.services import langgraph_service
from pydantic import BaseModel

# Configure logging
logger = logging.getLogger(__name__)

router = APIRouter()

class WorkflowInitParams(BaseModel):
    """Parameters for initializing the workflow including model and pipeline settings"""
    model_params: Dict[str, Any] = {}
    pipeline_params: Dict[str, Any] = {}

class RunWorkflowParams(BaseModel):
    """Parameters for running the workflow"""
    question: str

@router.post("/init_workflow")
def init_workflow(workflow_init_params: Optional[WorkflowInitParams] = None) -> dict:
    """
    Initialize a LangGraph workflow with the provided parameters.
    
    This endpoint sets up a workflow graph with agents for document processing,
    retrieval, script execution, generation, and evaluation. It configures the
    workflow based on the provided parameters or uses defaults if none are provided.

    Args:
        workflow_init_params (WorkflowInitParams, optional): Parameters for configuring the workflow,
            including model, pipeline, and workflow behavior settings.

    Returns:
        dict: A dictionary containing the response message indicating successful workflow initialization
            Example: {"message": "Workflow initialized successfully"}

    Raises:
        HTTPException: If there is an error during workflow initialization, with status code 400
            Example: HTTPException(status_code=400, detail="Failed to initialize workflow: <error details>")
    """
    if not workflow_init_params:
        workflow_init_params = WorkflowInitParams()
    
    # Call the service with parameters directly
    response = langgraph_service.init_workflow(
        model_params=workflow_init_params.model_params,
        pipeline_params=workflow_init_params.pipeline_params,
    )
    
    if "error" in response:
        raise HTTPException(status_code=400, detail=response["error"])
    return response

@router.post("/run_workflow")
def run_workflow(run_params: RunWorkflowParams) -> Dict[str, Any]:
    """
    Run the LangGraph workflow with the provided parameters.
    
    This endpoint executes the previously initialized workflow graph with the provided
    query and parameters. The workflow will process documents, retrieve relevant information,
    generate a response, potentially execute scripts, and evaluate the response quality.

    Args:
        run_params (RunWorkflowParams): Parameters for the workflow execution,
            including the user query, session ID, and execution settings.

    Returns:
        Dict[str, Any]: A dictionary containing the workflow execution results, including:
            - llm_output: The final text response generated by the workflow
            - execution_status: Information about any scripts that were executed
            - metadata: Additional information about the workflow execution

    Raises:
        HTTPException: If there is an error during workflow execution, with status code 400
            Example: HTTPException(status_code=400, detail="Failed to run workflow: <error details>")
    """
    # Logging the received parameters
    logger.info(f"Running workflow with question: {run_params.question}")
    
    response = langgraph_service.run_workflow(question=run_params.question)
    
    if "error" in response:
        raise HTTPException(status_code=400, detail=response["error"])
    return response

@router.get("/workflow_status")
def get_workflow_status() -> dict:
    """
    Get the current status of the LangGraph workflow.
    
    This endpoint returns information about whether the workflow is initialized
    and other relevant status information about the workflow configuration.

    Returns:
        dict: A dictionary containing status information about the workflow
            Example: {
                "initialized": true,
                "num_agents": 5,
                "use_tracing": true
            }

    Raises:
        HTTPException: If there is an error retrieving workflow status, with status code 400
            Example: HTTPException(status_code=400, detail="Failed to get workflow status: <error details>")

    Example:
        >>> get_workflow_status()
        {
            "initialized": true,
            "num_agents": 5,
            "use_tracing": true
        }
    """
    response = langgraph_service.get_workflow_status()
    if "error" in response:
        raise HTTPException(status_code=400, detail=response["error"])
    return response 